language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install -qq libjpeg-dev
  - sudo apt-get install -qq libhdf5-serial-dev

# command to install dependencies
install: 
  - pip install nose --use-mirrors
  - pip install numpy --use-mirrors
  - pip install numexpr --use-mirrors
  - pip install ipython --use-mirrors
  - pip install cython --use-mirrors
  - pip install tables --use-mmirrors
  - python setup.py install
  
# command to run tests
script: nosetests

